### ISSUE TITLE
Transfer ownership of this repository?

### ISSUE THREAD

**Issue by sircuri** [Ravadre/NLog.FSharp#4]
It looks like you have stopped working on this project for a while now. Do you want to transfer ownership of this repo to somebody else so we can continue working on it?

Also allow the community to re-use the package name on NuGet.

Thanks.

**Comment by bretthall** [comment]
@sircuri Seems like it's been long enough since you put in the comment above, maybe a fork is in order? Bummer that the nuget name wouldn't be able to be reused though.

**Comment by j-alexander** [comment]
Maybe we should see if the NLog team is interested in bringing the module into their core repo under an FSharp namespace?

**Comment by sircuri** [comment]
_I have made a request at NLog: https://github.com/NLog/NLog/issues/3865_

**(ticket has been rejected and is closed already)**

**Comment by Ravadre** [comment]
Hello,

I have not been accessing my Github account for a while. 
I'm very happy to see that my little project from a while back is still useful for some.

I will gladly transfer the rights to either NLog or @j-alexander is the NLog community will not be.

**Comment by sircuri** [comment]
NLog has no interest in this project as it is merely a wrapper and lacks any unit tests. The ticket I opened has been closed already.
